server:
  port: 6667
spring:
  application:
    name: demo
  datasource:
    druid:
      url: jdbc:p6spy:mysql://10.0.2.108:3306/test_nextop?useUnicode=true&characterEncoding=UTF-8
      username: ops
      password: jS0rarzFQIltwJCC
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      #filters: stat,wall,log4j
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # druid 监控配置  访问路径：http://ip:port/druid/login.html
      filter:
        # 用于统计监控信息。
        stat:
          enabled: true
          # 记录超过此指定时间的 慢sql 单位：ms
          slow-sql-millis: 1000
          # 合并相同sql的统计
          merge-sql: true
        slf4j:
          # 开启日志管理，监控页面可重置记录
          enabled: true
      # web应用 监控配置
      web-stat-filter:
        enabled: true
        # 能够监控单个url调用的sql列表
        profile-enable: true
        # 监控路径控制  eg: /admin/*
        url-pattern: /*
        # 不拦截的路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/stockDruid/*'
      # druid 监控页面入口控制
      stat-view-servlet:
        enabled: true
        # ip白名单 只有当前名单中的ip才能访问 1/27表示ip前27位相同即可
        allow: 0.0.0.0/0
        # ip黑名单，禁止访问的地址 优先级高于白名单
        deny:
        # druid 监控页面登录账号
        login-username: druid
        # druid 监控页面登录密码
        login-password: 123456
        # 监控页面访问路径配置
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: true
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 开启连接池回收
      remove-abandoned: true
      # 超时连接回收时间，单位秒
      remove-abandoned-timeout: 1800
mybatis-plus:
  # mapper配置文件路径，不填会报错：invalid bound statement (not found)
  mapper-locations: classpath:dao/*.xml
rocketmq:
  name-server: localhost:9876
