server:
  port: 6667
spring:
  application:
    name: demo
  datasource:
    druid:
      url: jdbc:p6spy:mysql://192.168.1.104:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      #filters: stat,wall,log4j
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # druid 监控配置  访问路径：http://ip:port/druid/login.html
      filter:
        # 用于统计监控信息。
        stat:
          enabled: true
          # 记录超过此指定时间的 慢sql 单位：ms
          slow-sql-millis: 1000
          # 合并相同sql的统计
          merge-sql: true
        slf4j:
          # 开启日志管理，监控页面可重置记录
          enabled: true
      # web应用 监控配置
      web-stat-filter:
        enabled: true
        # 能够监控单个url调用的sql列表
        profile-enable: true
        # 监控路径控制  eg: /admin/*
        url-pattern: /*
        # 不拦截的路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/stockDruid/*'
      # druid 监控页面入口控制
      stat-view-servlet:
        enabled: true
        # ip白名单 只有当前名单中的ip才能访问 1/27表示ip前27位相同即可
        allow: 0.0.0.0/0
        # ip黑名单，禁止访问的地址 优先级高于白名单
        deny:
        # druid 监控页面登录账号
        login-username: druid
        # druid 监控页面登录密码
        login-password: 123456
        # 监控页面访问路径配置
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: true
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 开启连接池回收
      remove-abandoned: true
      # 超时连接回收时间，单位秒
      remove-abandoned-timeout: 1800
  kafka:
    #指定kafka server的地址，集群配多个，中间，逗号隔开,10.0.1.123:9092
    bootstrap-servers: 10.0.1.237:9092,10.0.1.195:9092,10.0.1.103:9092
      #listener:
      # ack-mode:
      #  RECORD: 每处理一条commit一次
      #  BATCH(默认):每次poll的时候批量提交一次，频率取决于每次poll的调用频率
      #  TIME :每次间隔ackTime的时间去commit
      #  COUNT :累积达到ackCount次的ack去commit
      #  COUNT_TIME:ackTime或ackCount哪个条件先满足，就commit
      #  MANUAL:listener负责ack，但是背后也是批量上去
      #  MANUAL_IMMEDIATE:listner负责ack，每调用一次，就立即commit
      #ack-mode: manual
    #生产端配置
    producer:
      #客户端id 用于服务器日志记录
      #client-id: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
        #  0：broker 一接收到还没有写入磁盘就已经返回，当 broker 故障时有可能丢失数据；
        #  1： producer 等待 broker 的 ack， partition 的 leader 落盘成功后返回 ack，如果在 follower同步成功之前 leader 故障，那么将会丢失数据；
        #  -1（all） ： producer 等待 broker 的 ack， partition 的 leader 和 follower 全部落盘成功后才
        #  返回 ack。但是如果在 follower 同步完成后， broker 发送 ack 之前， leader 发生故障，那么会
      #   造成数据重复。
      acks: -1  #消息不丢失最大努力保证
      #只有数据积累到 batch.size字节之后， sender 才会发送数据
      #batch-size:
      # 失败后从试次数
      retries: 4
    #消费端配置
    consumer:
      #消费端客户端id 用于服务器日志记录
      #client-id: 101
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: nextop_dataflow_plat # 群组ID
      #消息是否自动提交，true 代表自动提交，false 代表关闭自动提交
      enable-auto-commit: false
      #自动提交的间隔时间，当前仅当在enable-auto-commit: true 的情况下生效
      #auto-commit-interval: 1000ms
      #auto-offset-reset: 生效条件换了消费者组的时候 或者 offset 已经被删掉了的失败
      #该参数有两个参数可选：earliest和latest 而默认值是lastest.
      # earliest 从最早开始消费.lastest 从最大提交的offset开始消费
      auto-offset-reset: earliest
      # 一次请求服务器等等的最大时长fetch-max-wait 与fetch-min-size二者满足一个即可返回.
      fetch-max-wait: 500
      #拉取满足的最小数量
      fetch-min-size: 10
      #一次拉取返回的最大数量
      max-poll-records: 50
mybatis-plus:
  # mapper配置文件路径，不填会报错：invalid bound statement (not found)
  mapper-locations: classpath:dao/*.xml
rocketmq:
  name-server: localhost:9876
